"""
Response Formatters for Customer Success FTE
Handles channel-specific response formatting
"""

from enum import Enum
from typing import Dict, Optional


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


def format_for_channel(response: str, channel: Channel, max_length: Optional[int] = None) -> str:
    """
    Format response appropriately for the channel.

    Args:
        response: The response text to format
        channel: The target channel
        max_length: Optional max length override

    Returns:
        Formatted response string
    """
    if channel == Channel.EMAIL:
        max_len = max_length or 2000
        return _format_email_response(response, max_len)
    elif channel == Channel.WHATSAPP:
        max_len = max_length or 1600
        return _format_whatsapp_response(response, max_len)
    else:  # web_form
        max_len = max_length or 1000
        return _format_webform_response(response, max_len)


def _format_email_response(response: str, max_length: int) -> str:
    """Format response for email channel."""
    if len(response) > max_length:
        response = response[:max_length - 3] + "..."

    return f"""Dear Customer,

Thank you for contacting TechCorp Support.

{response}

If you have any further questions, please don't hesitate to reply to this email.

Best regards,
TechCorp AI Support Team
---
Ticket Reference: {{ticket_id}}
This response was generated by our AI assistant. For complex issues, you can request human support."""


def _format_whatsapp_response(response: str, max_length: int) -> str:
    """Format response for WhatsApp channel."""
    # Keep it short for WhatsApp
    if len(response) > max_length:
        response = response[:max_length - 3] + "..."

    return f"{response}\n\n📱 Reply for more help or type 'human' for live support."


def _format_webform_response(response: str, max_length: int) -> str:
    """Format response for web form channel."""
    if len(response) > max_length:
        response = response[:max_length - 3] + "..."

    return f"""{response}

---
Need more help? Reply to this message or visit our support portal."""


def split_long_message(message: str, max_length: int = 1600) -> list[str]:
    """
    Split a long message into multiple parts if needed.

    Args:
        message: The message to split
        max_length: Maximum length per part

    Returns:
        List of message parts
    """
    if len(message) <= max_length:
        return [message]

    # Split into multiple messages
    messages = []
    current_part = ""

    # Split by sentences first
    sentences = message.split('. ')
    for sentence in sentences:
        sentence_with_period = sentence + '. ' if not sentence.endswith('.') else sentence

        if len(current_part + sentence_with_period) <= max_length:
            current_part += sentence_with_period
        else:
            # If adding this sentence would exceed the limit
            if current_part:
                messages.append(current_part.strip())
            # If the single sentence is longer than max_length, split it
            if len(sentence_with_period) > max_length:
                # Split the long sentence into smaller chunks
                chunks = [sentence_with_period[i:i+max_length]
                         for i in range(0, len(sentence_with_period), max_length)]
                messages.extend(chunks[:-1])  # Add all but the last chunk
                current_part = chunks[-1]  # Start new part with remaining
            else:
                current_part = sentence_with_period

    # Add the last part if there is one
    if current_part.strip():
        messages.append(current_part.strip())

    return messages


def format_customer_history(history: list[dict], max_entries: int = 5) -> str:
    """
    Format customer history for agent context.

    Args:
        history: List of interaction dictionaries
        max_entries: Maximum number of entries to include

    Returns:
        Formatted history string
    """
    if not history:
        return "No previous interactions found."

    formatted_history = f"Customer has {len(history)} previous interactions:\n\n"
    for i, interaction in enumerate(history[-max_entries:], 1):  # Show last X interactions
        formatted_history += f"{i}. Channel: {interaction.get('channel', 'unknown')}\n"
        formatted_history += f"   Content: {interaction.get('content', '')[:100]}...\n"
        formatted_history += f"   Role: {interaction.get('role', 'unknown')}\n"
        formatted_history += f"   Date: {interaction.get('created_at', 'unknown')}\n\n"

    return formatted_history


def format_knowledge_results(results: list[dict]) -> str:
    """
    Format knowledge base search results for the agent.

    Args:
        results: List of search result dictionaries

    Returns:
        Formatted results string
    """
    if not results:
        return "No relevant documentation found. Consider escalating to human support."

    formatted = []
    for result in results:
        title = result.get('title', 'Untitled')
        content = result.get('content', '')[:500]  # Limit content length
        similarity = result.get('similarity', 0)
        formatted.append(f"**{title}** (relevance: {similarity:.2f})\n{content}")

    return "\n\n---\n\n".join(formatted)


def format_ticket_info(ticket_data: dict) -> str:
    """
    Format ticket information for agent context.

    Args:
        ticket_data: Dictionary with ticket information

    Returns:
        Formatted ticket info string
    """
    return f"""
Ticket ID: {ticket_data.get('ticket_id', 'N/A')}
Customer: {ticket_data.get('customer_id', 'N/A')}
Channel: {ticket_data.get('channel', 'N/A')}
Priority: {ticket_data.get('priority', 'N/A')}
Category: {ticket_data.get('category', 'N/A')}
Status: {ticket_data.get('status', 'N/A')}
Created: {ticket_data.get('created_at', 'N/A')}
    """.strip()